# East West Germany

In [84]:
import os.path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
%matplotlib inline
from bs4 import BeautifulSoup
import webbrowser
import urllib.request
from lxml import html
import zipfile
import re
import string
import sys, os
from IPython.display import Image
import itertools

In [85]:
filepath = '../../data/analysis/complete_data.csv'

In [86]:
if not os.path.exists( filepath ):
    print("Missing dataset file")
else:
    df = pd.read_csv(filepath , encoding = "ISO-8859-1")
    print("File Read")

File Read

In [87]:
df.columns

Index(['Unnamed: 0', 'Year', 'Host_Country', 'Host_City', 'Summer', 'Winter',
       'Total_Males', 'Total_Females', 'Total_Athletes', 'Discipline', 'Sport',
       'Ath_Name', 'Gender', 'Home_Adv', 'Gold', 'Silver', 'Bronze',
       'Total_Medals', 'Ath_Rating', 'Ath_Rank', 'NOC', 'NOC_Males_Sent',
       'NOC_Females_Sent', 'NOC_Total_Sent', 'NOC_Gold', 'NOC_Silver',
       'NOC_Bronze', 'NOC_Total_Medals', 'NOC_Rating', 'NOC_Rank', 'Country',
       'Population', 'Males', 'Females', 'Life_Expectancy', 'GDP', 'Region',
       'Elevation', 'Area_SqKM', 'Centroid_Longitude', 'Centroid_Latitude',
       'Population_Density', 'CO2_Emissions', 'Methane_Emissions',
       'Nitrous_Oxide_Emisions', 'Total_Emissions', 'Emmisions_per_Capita',
       'Code', 'Lowest_Point', 'Highest_Point', 'Elevation_Range',
       'Education_Index'],
      dtype='object')

In [88]:
df = df.groupby('Host_City')[['Year','Summer']].last().reset_index()
df

         Host_City  Year  Summer
0      Albertville  1992   False
1           Athens  2004    True
2          Atlanta  1996    True
3        Barcelone  1992    True
4          Beijing  2008    True
5          Calgary  1988   False
6         Grenoble  1968   False
7        Innsbruck  1976   False
8      Lake Placid  1980   False
9      Lillehammer  1994   False
10          London  2012    True
11     Los Angeles  1984    True
12          Mexico  1968    True
13        Montréal  1976    True
14          Moscow  1980    True
15          Munich  1972    True
16          Nagano  1998   False
17             Rio  2016    True
18            Rome  1960    True
19  Salt Lake City  2002   False
20         Sapporo  1972   False
21        Sarajevo  1984   False
22           Seoul  1988    True
23           Sochi  2014   False
24    Squaw Valley  1960   False
25          Sydney  2000    True
26           Tokyo  1964    True
27           Turin  2006   False
28       Vancouver  2010   False

In [89]:
folders = []
for i in df.index:
    year = df.loc[i].Year
    city = df.loc[i].Host_City
    summ = 'Winter'
    if df.loc[i].Summer:
        summ = 'Summer'
    if city == 'Montréal':
        city = 'Montreal'
    folders.append(str(year)+"_"+city+"_"+summ)

In [90]:
path = '../../data/analysis/Games_Networks/{}/edges.csv'
paths = [path.format(i) for i in folders]
paths

['../../data/analysis/Games_Networks/1992_Albertville_Winter/edges.csv',
 '../../data/analysis/Games_Networks/2004_Athens_Summer/edges.csv',
 '../../data/analysis/Games_Networks/1996_Atlanta_Summer/edges.csv',
 '../../data/analysis/Games_Networks/1992_Barcelone_Summer/edges.csv',
 '../../data/analysis/Games_Networks/2008_Beijing_Summer/edges.csv',
 '../../data/analysis/Games_Networks/1988_Calgary_Winter/edges.csv',
 '../../data/analysis/Games_Networks/1968_Grenoble_Winter/edges.csv',
 '../../data/analysis/Games_Networks/1976_Innsbruck_Winter/edges.csv',
 '../../data/analysis/Games_Networks/1980_Lake Placid_Winter/edges.csv',
 '../../data/analysis/Games_Networks/1994_Lillehammer_Winter/edges.csv',
 '../../data/analysis/Games_Networks/2012_London_Summer/edges.csv',
 '../../data/analysis/Games_Networks/1984_Los Angeles_Summer/edges.csv',
 '../../data/analysis/Games_Networks/1968_Mexico_Summer/edges.csv',
 '../../data/analysis/Games_Networks/1976_Montreal_Summer/edges.csv',
 '../../data/analysis/Games_Networks/1980_Moscow_Summer/edges.csv',
 '../../data/analysis/Games_Networks/1972_Munich_Summer/edges.csv',
 '../../data/analysis/Games_Networks/1998_Nagano_Winter/edges.csv',
 '../../data/analysis/Games_Networks/2016_Rio_Summer/edges.csv',
 '../../data/analysis/Games_Networks/1960_Rome_Summer/edges.csv',
 '../../data/analysis/Games_Networks/2002_Salt Lake City_Winter/edges.csv',
 '../../data/analysis/Games_Networks/1972_Sapporo_Winter/edges.csv',
 '../../data/analysis/Games_Networks/1984_Sarajevo_Winter/edges.csv',
 '../../data/analysis/Games_Networks/1988_Seoul_Summer/edges.csv',
 '../../data/analysis/Games_Networks/2014_Sochi_Winter/edges.csv',
 '../../data/analysis/Games_Networks/1960_Squaw Valley_Winter/edges.csv',
 '../../data/analysis/Games_Networks/2000_Sydney_Summer/edges.csv',
 '../../data/analysis/Games_Networks/1964_Tokyo_Summer/edges.csv',
 '../../data/analysis/Games_Networks/2006_Turin_Winter/edges.csv',
 '../../data/analysis/Games_Networks/2010_Vancouver_Winter/edges.csv']

In [91]:
dfs =[]
for filepath in paths:
    if not os.path.exists( filepath ):
        print("Missing dataset file")
    else:
        try:
            dfs.append(pd.read_csv(filepath , encoding = "ISO-8859-1"))
            print("File Read")
        except:
            print("Error - "+filepath)

File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read
File Read

In [92]:
dfs[12].Source.unique()

array(['TUN', 'KEN', 'USA', 'ITA', 'FRG', 'URS', 'GBR', 'FRA', 'GDR',
       'AUS', 'TCH', 'HUN', 'NZL', 'ETH', 'MEX', 'POL', 'VEN', 'BRA',
       'UGA', 'KOR', 'JPN', 'BUL', 'ROU', 'YUG', 'FIN', 'ARG', 'DEN',
       'AUT', 'NOR', 'NED', 'SWE', 'BEL', 'SUI', 'IND', 'PAK', 'CAN',
       'IRI', 'MGL', 'TUR', 'GRE', 'TPE'], dtype=object)

In [94]:
relevant = dict()
for i in range(len(dfs)):
    temp = dfs[i]
    nocs = temp.Source.unique()
    noct = temp.Target.unique()
    
    if 'FRG' in nocs or 'FRG' in noct:
        key = df.loc[i].Host_City+"-"+str(df.loc[i].Year)
        print(key)

Calgary-1988
Grenoble-1968
Innsbruck-1976
Lake Placid-1980
Los Angeles-1984
Mexico-1968
Munich-1972
Sapporo-1972
Sarajevo-1984
Seoul-1988

  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS
  Source Target
0    AUS    AUS
1    AUS    URS
2    AUS    EUA
3    URS    AUS
4    URS    URS